Improve portability of make_custom_pi_os
- Use `which` to check for `gsed` and use it if available:
  macos ships with BSD sed which doesn't support `-i` for in-place
  editing
- get the primary group of the current user with `id -gn` instead
  of hardcoding it to `${USER}` - macos doesn't create a group
  with the same name as the user by default
- Add quotes around a bunch of variables to prevent globbing /
  word splitting
- Use `set -euo pipefail` to make the script fail on errors and
  undefined variables, rather than silently continuing
- Use '-s' flag with curl to prevent it from printing the download
  progress bar when retrieving version info
- Check we can retrieve the filename of the latest Raspbian image
  before downloading it
- Print out the URL of the image we're downloading

diff --git a/src/make_custom_pi_os b/src/make_custom_pi_os
--- a/src/make_custom_pi_os
+++ b/src/make_custom_pi_os
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+set -euo pipefail
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 source "$DIR/argparse.bash" || exit 1
 argparse "$@" <<EOF || exit 1
@@ -9,41 +10,44 @@ parser.add_argument('-g', '--get_image', action='store_true',
                     help='Pick a number [default %(default)s]')
 EOF
 
-echo Settings: 
+echo Settings:
 echo making dstro in "$DEST"
-
-DIST_NAME=$(basename "$DEST")
 
 for a in "${MULTIPLE[@]}"; do
     echo "  $a"
 done
 
-if [ -d ${DEST} ]; then
+if [ -d "${DEST}" ]; then
     echo "Error, folder already exists: ${DEST}"
     exit 1
 fi
 
-if [ -f ${DEST} ]; then
+if [ -f "${DEST}" ]; then
     echo "Error, file already exists: ${DEST}"
     exit 1
 fi
 
-cp -a ${DIR}/dist_generators/dist_example "${DEST}"
-chown $USER:$USER -R ${DEST}
+cp -a "${DIR}/dist_generators/dist_example" "${DEST}"
+chown -R "${USER}":"$(id -gn "${USER}")" "${DEST}"
 
-${DIR}/dist_generators/dist_example_script "${DEST}"
+"${DIR}/dist_generators/dist_example_script" "${DEST}"
 
 "$DIR/update-custompios-paths" "${DEST}/src"
 
-if [ $GET_IMAGE ]; then
-    echo "Downloading latest Raspbian image"
-    
-    CURRENT_RASPBIAN=$(curl https://downloads.raspberrypi.org/raspios_lite_armhf/images/ | grep raspios | tail -n 1 | awk -F "href=\"" '{print $2}' | awk -F "/" '{print $1}')
+if [ "$GET_IMAGE" ]; then
+    echo -n "Downloading latest Raspbian image"
+
+    CURRENT_RASPBIAN=$(curl -s https://downloads.raspberrypi.org/raspios_lite_armhf/images/ | grep raspios | tail -n 1 | awk -F "href=\"" '{print $2}' | awk -F "/" '{print $1}')
     if [ $? -ne 0 ]; then
-        echo "error getting date"
+        echo -e "\nerror getting date"
         exit 1
     fi
-    CURRENT_RASPBIAN_FILE=$(curl http://downloads.raspberrypi.org/raspios_lite_armhf/images/${CURRENT_RASPBIAN}/ | grep .xz | head -n 1 | awk -F "href=\"" '{print $2}' | awk -F "\">" '{print $1}')
-    curl -L -o "${DEST}/src/image/${CURRENT_RASPBIAN_FILE}" https://downloads.raspberrypi.org/raspios_lite_armhf/images/${CURRENT_RASPBIAN}/${CURRENT_RASPBIAN_FILE}
+    CURRENT_RASPBIAN_FILE="$(curl -s "http://downloads.raspberrypi.org/raspios_lite_armhf/images/${CURRENT_RASPBIAN}"/ | grep .xz | head -n 1 | awk -F "href=\"" '{print $2}' | awk -F "\">" '{print $1}')"
+    if [ $? -ne 0 ]; then
+        echo -e "\nerror getting file name"
+        exit 1
+    fi
+    CURRENT_RASPBIAN_URL="https://downloads.raspberrypi.org/raspios_lite_armhf/images/${CURRENT_RASPBIAN}/${CURRENT_RASPBIAN_FILE}"
+    echo " from ${CURRENT_RASPBIAN_URL}"
+    curl -L -o "${DEST}/src/image/${CURRENT_RASPBIAN_FILE}" "${CURRENT_RASPBIAN_URL}"
 fi
-
